apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prueba-js-stage

# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: prueba-js

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- configmap.yaml
# - ingress.yaml
# - githubsecret.yaml
