apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prueba-js
spec:
  rules:
  - host: 146.190.15.212
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prueba-js
            port:
              number: 80